@baseUrl = http://127.0.0.1/api/v1/payment
@cType = application/json
@password = password

### ROUTE API PAYMENT

### get request payment
get {{baseUrl}}
token: {{password}}

### INI BUAT GET DATA payment BY ID
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

### post request payment
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

{
    "order_id": "1",
    "gross_amount": "190000",
    "first_name": "fatwa",
    "last_name": "arrevi",
    "email": "arrevi@example.com",
    "phone": "0812652890657"
}

### put request payment by ID
Pput {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}

{
    "order_id": "5",
    "gross_amount": "200000",
    "first_name": "mawan ganteng",
    "last_name": "alwahyu",
    "email": "john.doe@example.com",
    "transaction_status": "okehh",
    "phone": "081234567890"
}

### delete request payment by ID
delete {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}