@baseUrl = http://127.0.0.1/api/v1/payment
@cType = application/json
@password = password

### ROUTE API PAYMENT

### get request payment
get {{baseUrl}}
token: {{password}}

### INI BUAT GET DATA payment BY ID
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

### post request payment
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

{
    "order_id": "1",
    "gross_amount": "15000",
    "first_name": "fatwa",
    "last_name": "arrevi",
    "email": "arrevi@example.com",
    "phone": "0812652890657"
}

### put request payment by ID
Pput {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}

{
    "order_id": "4",
    "gross_amount": "5000",
    "first_name": "fatwaa",
    "last_name": "arrevii",
    "email": "arrrevii@example.com",
    "transaction_status": "succes",
    "phone": "0812652890657"
}

### delete request payment by ID
delete {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}